language: go
sudo: false
go:
  - 1.11.x
before_install:
  - go get golang.org/x/lint/golint
  - go get honnef.co/go/tools/cmd/staticcheck
jobs:
  include:
    - script: make all
    - stage: Run Test Coverage
      script: make cover
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: Build Release
      script:
        - make release
        - echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        file:
          - cross/audit-darwin-amd64
          - cross/audit-darwin-amd64.md5
          - cross/audit-darwin-amd64.sha256
          - cross/audit-darwin-386
          - cross/audit-darwin-386.md5
          - cross/audit-darwin-386.sha256
          - cross/audit-freebsd-amd64
          - cross/audit-freebsd-amd64.md5
          - cross/audit-freebsd-amd64.sha256
          - cross/audit-freebsd-386
          - cross/audit-freebsd-386.md5
          - cross/audit-freebsd-386.sha256
          - cross/audit-linux-arm
          - cross/audit-linux-arm.md5
          - cross/audit-linux-arm.sha256
          - cross/audit-linux-arm64
          - cross/audit-linux-arm64.md5
          - cross/audit-linux-arm64.sha256
          - cross/audit-linux-amd64
          - cross/audit-linux-amd64.md5
          - cross/audit-linux-amd64.sha256
          - cross/audit-linux-386
          - cross/audit-linux-386.md5
          - cross/audit-linux-386.sha256
          - cross/audit-solaris-amd64
          - cross/audit-solaris-amd64.md5
          - cross/audit-solaris-amd64.sha256
          - cross/audit-windows-amd64
          - cross/audit-windows-amd64.md5
          - cross/audit-windows-amd64.sha256
          - cross/audit-windows-386
          - cross/audit-windows-386.md5
          - cross/audit-windows-386.sha256
        skip_cleanup: true
        on:
          tags: true
        api_key:
          secure: "f7K8UNz5XxXWJ0Abw3YvYF3sKFttS16pG0JQdCfnraTRxslmzih02iQgwIGsdQEK1swQDhyr857wl7O1RTpn3BXRVRDVKHZuBUx/mBt+yy0JFWB430RcPFeV2yQ1IT5YPk7EVbHtpsUPNKX/8URbSKN76OgC1Mml+Mg86ituIvyd+dMfUA95I1M7ng25UxdMVWMY5FRXXuZA2Xre6UHkDTCwtlInOs/7xqDQtD20h59+PNrcLlSmgMc3A0nTucBQ3wpv6VVOx6kkGTARqSaAGqH2oZxnDljs+ZgFP8ZIoWQTQR8gwuBXY/4cqsGzHYQzGrX4rODACH2gRtkwpHyHuTSx6FkJJFzOlhD5uhqPm4xvcb3Vju9bKMB+QGJYDo7BbtooGQDHo9mt9chdLdtOiZ/KCndMK+Do38ovP9qbFX0blV2oGRckOWNxYzSn1c5wGtzL1hF1culB8cbxR1no1xECRWShfWMrFFVXgH5EFxnhkrpz5NBeE9AUaOyGmIT1WNy0SaoZHTazBBzmiQsRToc2PnpTbm5J8ukoaR32m7Z7gwuPAb56LUW3L7/nxOOFmyYOrnpvzEjBlyIk6QfeEbX5UUal9dzxp8XaOxne7lJAqkrVwVibFK37YQDpJ0JMxets0vx3ocKs9FkFGD7mdneUldt2iMZy07W2mu9rm40="
