name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.x"
          cache: false

      - name: Get Go cached paths
        run: |
          echo "cache=$(go env GOCACHE)" >> $GITHUB_ENV
          echo "modcache=$(go env GOMODCACHE)" >> $GITHUB_ENV
         
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.cache }}
          key: setup-go-deps-${{ hashFiles('go.sum go.mod') }}
          restore-keys: |
            setup-go-deps-
        
      - name: Restore intermediate built files cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.modcache }}
          key: setup-go-build-${{ hashFiles('**/*.go') }}
          restore-keys: |
            setup-go-build-

      - name: Cached files stats
        run: |
          echo 'Cache build artefacts size (Mb):'
          du -m -s ${{ env.cache }}
          echo 'Cached dependencies size (Mb):'
          du -m -s ${{ env.modcache }}
            
      - name: get
        run: |
          go get

      - name: build
        run: |
          go build
